# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-US"
title                    : "Ranjith Kumar"
title_separator          : "-"
name                     : "Ranjith Kumar"
description              : "A central location where I can express myself through a personal blog and where I can display the projects I've been working on over the last couple of years."
url                      : "https://ranjith7214.github.io"
baseurl                  : 
gh_repo                  : "https://github.com/ranjith7214/ranjith7214.github.io"
teaser                   : "profile.jpg" # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              :  false # true, false (default)
words_per_minute         :  200
comments:
  provider               : "disqus" # false (default), "disqus", "facebook", "google-plus", custom"
  disqus:
    shortname            : "ranjith7214"
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : "dark" # "light" (default), "dark"

# SEO Related
google_site_verification : 
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               :  ""
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : "google" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "G-CFLT4WQRCN"

# Google AdSense
google_ad_client         :
google_ad_slot           :


# Site Author
author:
  name             : "Ranjith Kumar"
  avatar           : "profile.jpg"
  bio              : "exploring robotics applications of deep learning from vision, action to reasoning. Cricket enthusiast. Pasionately curious about the world around me."
  location         : "Chennai, India"
  email            : "ranjith7214@gmail.com"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         : 
  foursquare       :
  github           : "ranjith7214"
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : "ranjithkumar7214"
  pinterest        :
  soundcloud       :
  stackoverflow    : 
  steam            :
  tumblr           :
  twitter          : "ranjith7214"
  vine             :
  weibo            :
  xing             :
  youtube          :


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: US/Eastern


# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
categories:
  type: liquid
  path: /categories/
tags:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Pages
include: ["_pages"]

# Collections
collections:
    multi-agent-robust-pgo:
      output: true
      permalink: /:collection/:path/
    autonomous-drone:
      output: true
      permalink: /:collection/:path/
    cronus:
      output: true
      permalink: /:collection/:path/
    micromouse:
      output: true
      permalink: /:collection/:path/
    IRC:
      output: true
      permalink: /:collection/:path/

defaults:

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true

  # _multirobot
  - scope:
      path: ""
      type: multi-agent-robust-pgo
    values:
      layout: single
      author_profile: false
      read_time: true
      share: true
      sidebar:
         nav: multi-agent-robust-pgo

  #autonomous_drone
  - scope:
      path: ""
      type: autonomous-drone
    values:
      layout: single
      author_profile: false
      read_time: true
      share: true
      sidebar:
          nav: autonomous-drone
          
  # #cronus
  # - scope:
  #     path: ""
  #     type: cronus
  #   values:
  #     layout: single
  #     author_profile: false
  #     read_time: true
  #     share: true
  #     sidebar:
  #         nav: cronus

  # #micromouse
  # - scope:
  #     path: ""
  #     type: micromouse
  #   values:
  #     layout: single
  #     author_profile: false
  #     read_time: true
  #     share: true
  #     sidebar:
  #         nav: micromouse
  
  # # Internation robotics challenge
  # - scope:
  #     path: ""
  #     type: IRC
  #   values:
  #     layout: single
  #     author_profile: false
  #     read_time: true
  #     share: true
  #     sidebar:
  #         nav: IRC
    
